# Generated by Django 4.0.4 on 2022-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('locale', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(upload_to='images/', verbose_name='Icon')),
                ('isdefault', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10, verbose_name='Is Default')),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10, verbose_name='Status')),
            ],
        ),
    ]
