# Generated by Django 4.0.4 on 2022-07-06 13:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(default=None, max_length=100, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='enabled', max_length=10)),
            ],
        ),
    ]
