# Generated by Django 4.0.4 on 2022-07-07 04:38

import Block.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0002_language_created_at_language_updated_at'),
        ('Block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='content',
        ),
        migrations.RemoveField(
            model_name='block',
            name='title',
        ),
        migrations.AddField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10),
        ),
        migrations.CreateModel(
            name='BlockLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', tinymce.models.HTMLField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Block.block')),
                ('language', models.ForeignKey(default=Block.models.lan, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
        ),
    ]
