# Generated by Django 4.0.4 on 2022-07-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0002_language_created_at_language_updated_at'),
        ('Block', '0002_remove_block_content_remove_block_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockLanguage',
            new_name='BlockTranslation',
        ),
    ]
