# Generated by Django 4.0.4 on 2022-07-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0003_rename_blocklanguage_blocktranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocktranslation',
            old_name='id',
            new_name='btid',
        ),
    ]
