# Generated by Django 4.0.4 on 2022-07-07 09:43

import Banner.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0002_language_created_at_language_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('sortorder', models.IntegerField()),
                ('isfeatured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('bg', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=10)),
                ('shortorder', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('btid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', tinymce.models.HTMLField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
                ('bannergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
                ('language', models.ForeignKey(default=Banner.models.lan, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('biid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image Upload')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
                ('bannergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
            ],
        ),
        migrations.CreateModel(
            name='BannerGroupTranslation',
            fields=[
                ('bgtid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bannergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
                ('language', models.ForeignKey(default=Banner.models.lan, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='bannergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup'),
        ),
    ]
