# Generated by Django 4.0.4 on 2022-07-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannertranslation',
            name='bannergroup',
        ),
    ]
