# Generated by Django 4.0.4 on 2022-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0002_remove_bannertranslation_bannergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='url',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
