# Generated by Django 4.0.4 on 2022-07-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0003_bannerimage_url_alter_bannerimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannergroup',
            old_name='shortorder',
            new_name='sortorder',
        ),
    ]
