# Generated by Django 4.0.4 on 2022-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0005_rename_bg_bannergroup_bgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroup',
            name='sortorder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bannergrouptranslation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
