# Generated by Django 4.0.4 on 2022-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0007_remove_banner_bannergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroup',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
