# Generated by Django 4.0.4 on 2022-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0010_remove_banner_bannergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
