# Generated by Django 4.0.4 on 2022-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=200, verbose_name='Code*')),
                ('inputtype', models.CharField(choices=[('Textbox', 'Textbox'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Boolean', 'Boolean'), ('Textarea', 'Textarea'), ('Multi-select', 'Multi-select')], max_length=200, verbose_name='Input Type*')),
                ('isrequest', models.BooleanField(default=False, verbose_name='Is Request*')),
            ],
        ),
    ]
