# Generated by Django 4.0.4 on 2022-06-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=200, unique=True, verbose_name='Code')),
                ('inputtype', models.CharField(choices=[('Textbox', 'Textbox'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Boolean', 'Boolean'), ('Textarea', 'Textarea'), ('Multi-select', 'Multi-select'), ('Select', 'Select')], max_length=200, verbose_name='Input Type')),
                ('isrequest', models.BooleanField(default=False, verbose_name='Is Request')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coustomoption', models.CharField(max_length=200, unique=True, verbose_name='Custom Option')),
                ('sortorder', models.IntegerField(verbose_name='Sort Order')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('otid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.option')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.attribute')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
        ),
    ]
