# Generated by Django 4.0.4 on 2022-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='code',
            field=models.SlugField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='inputtype',
            field=models.CharField(choices=[('Textbox', 'Textbox'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Boolean', 'Boolean'), ('Textarea', 'Textarea'), ('Multi-select', 'Multi-select')], max_length=200, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='isrequest',
            field=models.BooleanField(default=False, verbose_name='Is Request'),
        ),
    ]
