# Generated by Django 4.0.4 on 2022-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0002_rename_id_option_optionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='isrequest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, max_length=10, verbose_name='Is Request'),
        ),
    ]
