# Generated by Django 4.0.4 on 2022-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0002_alter_attribute_code_alter_attribute_inputtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='inputtype',
            field=models.CharField(choices=[('Textbox', 'Textbox'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Boolean', 'Boolean'), ('Textarea', 'Textarea'), ('Multi-select', 'Multi-select'), ('Select', 'Select')], max_length=200, verbose_name='Input Type'),
        ),
    ]
