# Generated by Django 4.0.4 on 2022-06-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0003_alter_attribute_isrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetranslation',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributetranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='option',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='optiontranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='optiontranslation',
            name='option',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeTranslation',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionTranslation',
        ),
    ]
