# Generated by Django 4.0.4 on 2022-05-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0001_initial'),
        ('Attribute', '0003_alter_attribute_inputtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coustomoption', models.CharField(max_length=200, verbose_name='Custom Option')),
                ('sortorder', models.IntegerField(verbose_name='Sort Order')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.option')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.attribute')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
        ),
    ]
