# Generated by Django 4.0.4 on 2022-06-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='Is Default?'),
        ),
    ]
