# Generated by Django 4.0.4 on 2022-06-20 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0006_alter_option_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
