# Generated by Django 4.0.4 on 2022-06-20 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0009_remove_attribute_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
