# Generated by Django 4.0.4 on 2022-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attribute', '0010_attribute_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
