# Generated by Django 4.0.4 on 2022-05-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attribute', '0002_alter_attribute_code_alter_attribute_inputtype_and_more'),
        ('Language', '0001_initial'),
        ('Option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attribute.attribute')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Option.option')),
            ],
        ),
    ]
