# Generated by Django 4.0.4 on 2022-06-07 04:50

import Pages.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10, verbose_name='Status')),
                ('sortorder', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
        ),
        migrations.CreateModel(
            name='PageLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('language', models.ForeignKey(default=Pages.models.lan, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.pages')),
            ],
        ),
    ]
