# Generated by Django 4.0.4 on 2022-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_pagelanguage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelanguage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
