# Generated by Django 4.0.4 on 2022-06-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('isdefault', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('satatename', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('profileimg', models.ImageField(null=True, upload_to='images/', verbose_name='Profile Image')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('emailvarifaction', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10, null=True, verbose_name='Email Varifaction')),
                ('emailvarificationdate', models.DateTimeField(null=True, verbose_name='Varification Date')),
                ('phoneno', models.IntegerField(verbose_name='Phone Number')),
                ('password', models.CharField(max_length=8, verbose_name='Password')),
                ('confirmpassword', models.CharField(max_length=8, verbose_name='Confirm Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customergroup')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('statename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.state')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('streetname', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=200)),
                ('unitno', models.CharField(max_length=200)),
                ('postalcode', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('isdefault', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10, null=True, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.city')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.state')),
            ],
        ),
    ]
