# Generated by Django 4.0.4 on 2022-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_address_customer_alter_customer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='confirmpassword',
            field=models.CharField(max_length=24, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=24, verbose_name='Password'),
        ),
    ]
