# Generated by Django 4.0.4 on 2022-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_code_alter_customer_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirmpassword',
            field=models.CharField(max_length=200, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
    ]
