# Generated by Django 4.0.4 on 2022-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
