# Generated by Django 4.0.4 on 2022-07-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
