# Generated by Django 4.0.4 on 2022-07-05 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 12, 27, 8, 825159), null=True),
        ),
    ]
