# Generated by Django 4.0.4 on 2022-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coustomoption', models.CharField(max_length=200, verbose_name='Custom Option')),
                ('sortorder', models.IntegerField(verbose_name='Sort Order')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
            ],
        ),
    ]
